### ISSUE TITLE
General Package/Environment and Running Issues

### ISSUE THREAD

**Issue by mdsjazz-exp** [deeplearning-wisc/npos#10]
Hello! I hope you are all having a lovely day.

I've wanted to pull and run a couple of the demo experiments from this repo, and I have questions about the setup and run procedure outlined in the front page README.md. I understand that this repo is likely in-progress, but I wanted to share my experiences as I work through them. I may write some pull requests to accommodate if you would be open to that!

I am working on ubuntu 20.04 with CUDA version 12+ on a machine where I don't have  admin (and therefore sudo) privileges.

--------

**Setting up the Packages/Environment:**
I followed the directions and installed only the following:

1. Set up conda environment called "npos" with python==3.8 and its own pip
`conda create -n npos python==3.8 pip`
2. Pip installed pytorch==1.11
`pip install pytorch==1.11`
3. Visited the CLIP page and followed their installation instructions, removing the torch installation, and removing the cudatoolkit specification since my cuda is newer. (https://github.com/openai/CLIP)
`conda install -y -c pytorch torchvision cudatoolkit`
`pip install ftfy regex tqdm`
`pip install git+https://github.com/openai/CLIP.git`
4. Visited the faiss page and followed their installation instructions
`conda install -y -c pytorch faiss-gpu`

After these steps, I run the script `sh train_npos_imagenet_100.sh` and receive the following errors:
`ModuleNotFoundError: No module named 'umap'`
solved with: `pip install umap`
`ModuleNotFoundError: No module named 'sklearn'`
solved with `pip install scikit-learn`

If I try `cd /path/to/npos/training_from_scratch; sh train_npos_imagenet100.sh`, I get the following:

`ModuleNotFoundError: No module named 'tensorboard_logger'`
`pip install tensorboard-logger`

`ModuleNotFoundError: No module named 'tensorflow'`
`pip install tensorflow`

These aren't that big of a deal, but I wonder what the other environment requirements are the further I get in the script, and a more automated manner of setting up the environments (requirements.txt, setup.cfg, Dockerfile that installs all of the packages including those on github) would be appreciated! I want to make sure that my package versions are set up so that these tools can work cohesively on other (my) machines.

--------

**Running the scripts**
After solving the environment issues so far, I run `sh train_npos_imagenet_100.sh` and get:
`FileNotFoundError: [Errno 2] No such file or directory: '/nobackup-slow/taoleitian/CLIP_visual_feature/ImageNet-100/10/train/feature.pt'`.

This makes me wonder what this is--is this a path that is personal to Leitian Tao's computer or user account? Considering that I am working on a different machine that I don't have sudo on, is it possible to have these paths set in configs?

Further, if I run `sh train_npos_imagenet100.sh`, I get the following:

`FileNotFoundError: [Errno 2] No such file or directory: '/nobackup-slow/dataset/ILSVRC-2012/val'`

-------

Because I would like to run a couple experiments with NPOS, I want to work through fixing a couple of these and making the work more reproducible on my computer. Would you be interested if I were to send some of these changes via some pull requests?

Thanks again! Very interested in some of the findings in your papers and would love to to email about the subject material in addition.

**Comment by taoleitian** [comment]
Thanks for your interest in our work.

For Setting up the Packages/Environment, I will export which packages are used in our running environment and upload them later.

For Running the scripts, the file cannot be uploaded because it is too large. You can refer to the feature_extraction_im100.py to generate the corresponding feature file yourself.
