### ISSUE TITLE
Release a ImageNet-1K trained model

### ISSUE THREAD

**Issue by AtsuMiyai** [deeplearning-wisc/npos#11]
Hi. Thanks for sharing the code for exciting work!
I would like to reproduce the results of ImageNet-1K pre-trained models in the original paper. However, I am having trouble reproducing it.　This is because 1. the provided code and the training method of the original paper are slightly different; 2. there are some minor errors in the provided code train_npos_imagenet_1k.sh (e.g., --dataset ImageNet-100).

So, could you please send me the ImageNet-1K pre-trained model? By providing a pre-trained model of ImageNet-1K, I consider that a lot of subsequent work could use your smart work as a baseline.
Thanks for your cooperation.

**Comment by taoleitian** [comment]
Thanks for your attention to our work. The checkpoint has been uploaded on Google drive 

https://drive.google.com/file/d/1nleU7JL12NSvOLcWdOIN9XSkWFSijhXc/view
