### ISSUE TITLE
Qestion about ID dataset ImageNet-100

### ISSUE THREAD

**Issue by Esther-PAN** [deeplearning-wisc/npos#15]
Hi, I have a question regarding the ID dataset used for training. It is mentioned in the paper that ImageNet-100 is obtained by randomly selecting 100 classes from ImageNet-1k. Could you provide the code for selecting these 100 classes? Also，I noticed that the 100 selected categories you used are listed in the appendix. Do I need to follow the exact same setup when reproducing the results?

**Comment by taoleitian** [comment]
Thanks for your interest in our work.

The 100 classes ID in ImageNet has been provided in the paper. Regarding your second question, while it is generally recommended to follow the exact same setup as described in the paper when reproducing results, it is not always strictly necessary. If you are interested in comparing your results to those reported in the paper, it would be best to use the same 100 categories selected by the authors. However, if you are interested in exploring the performance of the model on a different subset of ImageNet-1k classes, you can certainly do so, but you should be aware that your results may not be directly comparable to those reported in the paper.

**Comment by Esther-PAN** [comment]
Thank you for your enthusiastic response. Your work has given me great inspiration!

**Comment by Esther-PAN** [comment]
Hi, I have one more question. What is the backbone used in the table1 "OOD detection performance on ImageNet-100 as ID“?
