### ISSUE TITLE
question about expeiments details 

### ISSUE THREAD

**Issue by Esther-PAN** [deeplearning-wisc/npos#17]
Thanks for the great work!
I got questions regarding the experimental details. In Section 4.2 of the paper, it is mentioned that "All the other baseline methods are fine-tuned using the same pre-trained model weights (i.e., CLIP-B/16) and the same number of layers as ours."
However, I am not sure how the different methods were compared, I couldn't find the relevant content in the provided code either. Could you please explain how the comparison was conducted for the "energy"? Also, If you could provide the code, it would be greatly appreciated！

**Comment by taoleitian** [comment]
Thank you for your attention. The standard method is that we add a fully connected layer after ViT to directly fine-tuning CLIP. That is to say, the training parameters include the limited parameters in the ViT backbone and the parameters of the fully connected layer. Then use the standard OOD score in other papers, i.e. energy, to test.
