### ISSUE TITLE
Request 10_train.txt and 10_val.txt

### ISSUE THREAD

**Issue by Gidear** [deeplearning-wisc/npos#18]
Dear respected developers, thank you very much for your work
Could you please provide the files `10_train.txt `and `10_val.txt` mentioned in the `train_npos.py` and i want to refine-tune ImageNet-1000?
I consider that a lot of subsequent work could use your smart work as a baseline.
Thanks for your cooperation.

**Comment by taoleitian** [comment]
Thanks for your attention. Here is the link for 10_train.txt and 10_val.txt https://drive.google.com/file/d/10QoDFyOuJAgYlzO7PzW0_sFmKOMIYE2U/view?usp=drive_link. We have added this link into readme.
