### ISSUE TITLE
checkpoint for cifar100 pretrain model

### ISSUE THREAD

**Issue by Esther-PAN** [deeplearning-wisc/npos#19]
Dear respected developers, thank you very much for your work.
I would like to reproduce the results but I meet some troubles, so could you please provide checkpoint for cifar100 pretrain model?

**Comment by taoleitian** [comment]
Thanks for your interest. We already uploaded the ckpt. Here is the link for your reference https://drive.google.com/file/d/1Vd5eoUHmQtlsfMxcH3evFcUiYYdyqvNU/view.
