### ISSUE TITLE
can not reimplement

### ISSUE THREAD

**Issue by draymondLiu** [deeplearning-wisc/npos#2]
Hi, I can not reimplement your code and find the "train_npos_cifar10.sh" file. Is it normal? thanks

**Comment by draymondLiu** [comment]
I want to test on the CIFAR-10 datasets, please provide some support!

**Comment by taoleitian** [comment]
Hi, thanks for your attention for our work. We are still working on the code and haven't uploaded the latest version yet. If it is completed, you will be informed immediately.

**Comment by taoleitian** [comment]
We have completed the update, please refer to the new file.
