### ISSUE TITLE
About experiments' results

### ISSUE THREAD

**Issue by Cverchen** [deeplearning-wisc/npos#20]
Hello, @taoleitian.
I use the checkpoint of CIFAR100 and run test_npos_cifar100.sh
but i get the following results:
![image](https://github.com/deeplearning-wisc/npos/assets/103486994/1b542a29-8d86-4e72-b525-1c515a554282)
And i reproduce the training method and test, the results are still strange.
I look forward to your suggestions. Thanks!

**Comment by taoleitian** [comment]
Could you please share more information?

**Comment by Cverchen** [comment]
I follow the evaluation steps in ReadMe.md, and i also use your reported checkpoint of CIFAR100, and I use it to test the OOD detection, but the results are strange: SVHN AUROC:100 but the  performance of other OOD datasets is around 50.

**Comment by taoleitian** [comment]
could you please check the dataset loading?

**Comment by Cverchen** [comment]
But the performance of other datasets: like Textures auroc: 40% is also strange?

**Comment by taoleitian** [comment]
hmmm, there is so little information that it seems difficult for me to judge. I just tested this on my own code and the results seem to be correct.

**Comment by Cverchen** [comment]
python eval_ood_detection.py --in_dataset CIFAR-100 --model resnet34 --ckpt CIFAR100_scratch.pt --K 300

is this your running command? The eval_ood_detection.py in this project  is also used, but i don't get the correct result. The datasets are normal, which i have checked.

**Comment by taoleitian** [comment]
Could you please show me the prob of the prediction?
