### ISSUE TITLE
How can train CLIP-based model ?

### ISSUE THREAD

**Issue by ma-kjh** [deeplearning-wisc/npos#21]
Hi. Thank you for sharing code.

i wonder how can i extract feature of imagenet_100

feature_extraction is not working.

"We also provide pretrained features for [ImageNet-100](https://drive.google.com/drive/folders/1rkXQYHcaITZCj55OLNXqy_b-yjktONrn?usp=share_link)."

There is only CIFAR10 checkpoints that link.

Thank you

**Comment by taoleitian** [comment]
I think you can directly modify the code to exact the feature from ImageNet-100.

**Comment by ma-kjh** [comment]
Thank you
