### ISSUE TITLE
Where is the source code of  the function "generate_outliers"

### ISSUE THREAD

**Issue by adaxigua** [deeplearning-wisc/npos#5]
https://github.com/deeplearning-wisc/npos/blob/f70b5435c2b228bfcc7b06ac50f4833bdabe7f97/training_from_sctrach/CIFAR/train_CIFAR10.py#L24

It seems that the function "generate_outliers" is important. While I couldn't find it implement. 

I have tried to do "pip install KNN" （https://pypi.org/project/KNN/）. But there is no target.

What's more, I am interested in the implement of "we further perform a filtering process by selecting the virtual outlier in V_i with the highest k-NN distance" in the paper. 

Thanks!

**Comment by taoleitian** [comment]
Thanks for your interest in our work. 

Sorry for the mistake! We have reuploaded the file of generate_outliers. You can pay attention to the new file for the implementation.

https://github.com/deeplearning-wisc/npos/blob/90ba109d5debdf426bea637416e8cdf02cfb41c2/training_from_sctrach/CIFAR/KNN.py#L89

The current version of the code is not perfect, we are still cleaning up it. Maybe the last version is more informative for reference.
