### ISSUE TITLE
about imagenet-100 dataset 

### ISSUE THREAD

**Issue by tjl1** [deeplearning-wisc/npos#7]
Hi, Thanks for the great work!

I have a question about the imagenet-100 dataset.  I download the imagenet-1k,  and the training data set has been divided into 1000 files, of which I can easily access the 100 categories. 

But for the validation data set, all the images are put in one folder. How do I get the images of the 100 classes in the validation data set, or do I just compare the entire validation data set as a normal class to other data sets?

![image](https://user-images.githubusercontent.com/52659915/229268464-8752b6da-e49b-4dfb-b0ca-88759a26f596.png)

![image](https://user-images.githubusercontent.com/52659915/229268456-7dd4f6d7-8943-47dd-83b2-8a88032be653.png)

**Comment by taoleitian** [comment]
Every 50 images belong to a class. Maybe you should divide into fifty folders.

**Comment by tjl1** [comment]
感谢回答。
我还是不太明白你的意思，我想问的是在imagenet100上，你们是使用哪些图片作为验证集。我下载的imagenet1k的验证集里图片并没有分类，该如何找到那100个类对应的验证集。
