### ISSUE TITLE
Mismatch between input argument and function argument?

### ISSUE THREAD

**Issue by zjysteven** [deeplearning-wisc/npos#9]
Hi Leitian,

```
python train_CIFAR10.py --in-dataset CIFAR-10 --model resnet18 --T 0.1 --sample_from 600 --K 300 --learning_rate 0.1 --batch-size 256 --cov_mat 0.1 --start-epoch 200 --ID_points_num 200
```
https://github.com/deeplearning-wisc/npos/blob/c1e04d8e61a98d7235919084dac1b2f7f5264358/training_from_scratch/train_CIFAR10.py#L88

From the above scripts I assume that the desired `ID_points_num` should be 200 for CIFAR-10. However, this argument isn't actually passed to the function in the training script as below.

https://github.com/deeplearning-wisc/npos/blob/c1e04d8e61a98d7235919084dac1b2f7f5264358/training_from_scratch/train_CIFAR10.py#L294

**Comment by zjysteven** [comment]
The same issue also applies to `T` and `temp`.
https://github.com/deeplearning-wisc/npos/blob/c1e04d8e61a98d7235919084dac1b2f7f5264358/training_from_scratch/train_CIFAR10.py#L71
https://github.com/deeplearning-wisc/npos/blob/c1e04d8e61a98d7235919084dac1b2f7f5264358/training_from_scratch/train_CIFAR10.py#L82
https://github.com/deeplearning-wisc/npos/blob/c1e04d8e61a98d7235919084dac1b2f7f5264358/training_from_scratch/train_CIFAR10.py#L197-L198

**Comment by taoleitian** [comment]
Thank you for your interest in our work.

Sorry, NPOS involves too many related parameters, so it may be that the cleaning was not done in time during the finishing process. , which caused corresponding confusion. I have updated the relevant settings.

If you have any questions, please let me know in time.
